package work.iwansyng.iwansyng.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;
import work.iwansyng.iwansyng.models.*;
import work.iwansyng.iwansyng.models.quiz.*;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.net.URI;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

@Controller // This means that this class is a Controller
public class MainController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private final UserRepository userRepository;

    @Autowired
    RoleRepository roleRepository;

    @Autowired
    private PasswordEncoder passwordEncoder;

    public MainController(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    @GetMapping(path = "/")
    public String home() { return "index";  }

    @GetMapping(path = "/index")
    public String index() { return "index";  }

    @GetMapping(path = "/Training/Java")
    public String trainingJava() { return "/login";  }

    @GetMapping(path = "/login")
    public String login() { return "/login";  }

//    @GetMapping(path = "/hello")
//    public String hello() { return "/hello";  }

    @GetMapping(path = "/admin")
    public String admin() { return "/admin";  }

    @GetMapping(path = "/user")
    public String user() { return "/user";  }

    @RequestMapping("/hello")
    public void loginPageRedirect(HttpServletRequest request,
                                  HttpServletResponse response,
                                  Authentication authResult) throws IOException, ServletException {

        List<String> roles = authResult.getAuthorities()
                        .stream()
                        .map((g) -> g.getAuthority())
                        .collect(Collectors.toList());

        if (roles.contains("ADMIN")){
            response.sendRedirect(response.encodeRedirectURL(request.getContextPath() + "/admin"));
        }
        else if (roles.contains("USER")) {
            response.sendRedirect(response.encodeRedirectURL(request.getContextPath() + "/user"));
        }
    }

    @PostMapping(path="/add_user", consumes = "application/json", produces = "application/json") // Map ONLY POST Requests
    public String addNewUser (@RequestParam String firstName,
                              @RequestParam String lastName,
                              @RequestParam String userName,
                              @RequestParam String passWord,
                              HttpServletRequest request,
                              HttpServletResponse response) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User user = new User();
        user.setFirstName(firstName);
        user.setLastName(lastName);
        user.setUsername(userName);
        user.setPassword(passWord);
        user.setActive(true);
//        user.setRole(roleRepository.findByRoleName("USER"));

        userRepository.save(user);

        response.setStatus(HttpServletResponse.SC_OK);

        return response.getContentType();
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users

        User user = new User();
        user.setFirstName("maris");
        user.setLastName("krastins");
        user.setUsername("student");
//        user.setPassword("student007");
        user.setPassword(passwordEncoder.encode("student007"));
        user.setActive(true);
//        user.setRole(roleRepository.findByRoleName("USER"));

        userRepository.save(user);

        User user1 = new User();
        user1.setFirstName("Janis");
        user1.setLastName("Kalnins");
        user1.setUsername("teacher");
//        user1.setPassword("admin1234");
        user1.setPassword(passwordEncoder.encode("admin1234"));
        user1.setActive(true);
//        user1.setRole(roleRepository.findByRoleName("ADMIN"));

        userRepository.save(user1);

        return userRepository.findAll();
    }

    @GetMapping(path="/two_users")
    public @ResponseBody Iterable<User> getAllUsersOne() {
        // This returns a JSON or XML with the users

        User user2 = new User();
        user2.setFirstName("regina");
        user2.setLastName("brunevica");
        user2.setUsername("u01");
        user2.setPassword(passwordEncoder.encode("student008"));
        user2.setActive(true);

        user2.addRole(roleRepository.findByRoleName("USER"));

        userRepository.save(user2);

        User user3 = new User();
        user3.setFirstName("Janis");
        user3.setLastName("Zagorskis");
        user3.setUsername("admin");
        user3.setPassword(passwordEncoder.encode("admin5678"));
        user3.setActive(true);

        user3.addRole(roleRepository.findByRoleName("ADMIN"));

        userRepository.save(user3);

        return userRepository.findAll();
    }
}