package work.iwansyng.iwansyng.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import work.iwansyng.iwansyng.models.Instructor;
import work.iwansyng.iwansyng.models.Student;
import work.iwansyng.iwansyng.models.User;
import work.iwansyng.iwansyng.models.UserRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping(path="/add_student") // Map ONLY POST Requests
    public @ResponseBody
    String addNewStudent (@RequestParam String firstName
            , @RequestParam String lastName,
                       @RequestParam String userName,
                       @RequestParam String password) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Student n = new Student();
        n.setFirstName(firstName);
        n.setLastName(lastName);
        n.setUserName(userName);
        n.setPassword(password);
        userRepository.save(n);
        return "Saved";
    }

    @PostMapping(path="/add_instructor") // Map ONLY POST Requests
    public @ResponseBody
    String addNewInstructor (@RequestParam String firstName
            , @RequestParam String lastName,
                          @RequestParam String userName,
                          @RequestParam String password) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Instructor n = new Instructor();
        n.setFirstName(firstName);
        n.setLastName(lastName);
        n.setUserName(userName);
        n.setPassword(password);
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}