@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": ""
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "work.iwansyng.iwansyng",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false // root node is included
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "work.iwansyng.iwansyng.controller.AdminController"
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_567592198 { 
   	label=iwansyng
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1744458898 { 
   	label=iwansyng
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   AdminController304157657[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AdminController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   courseRepository: CourseRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   instructorRepository: InstructorRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   studentRepository: StudentRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userRepository: UserRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userService: IwanSyngUserService [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ adminHome(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ adminHomePage(username: String, principal: Principal): ModelAndView</TD></TR>
<TR><TD ALIGN="LEFT" >+ createNewAdminUser(user: User, bindingResult: BindingResult): ModelAndView</TD></TR>
<TR><TD ALIGN="LEFT" >+ createNewCourse(): ModelAndView</TD></TR>
<TR><TD ALIGN="LEFT" >- getOptionalName(objectName: String): Optional&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ registrationAdmin(): ModelAndView</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    

    
}
@enduml